name: Eval script

on:
  pull_request_target:
    branches: [ actions_test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Checkout Eval scripts
      run: git clone ${{secrets.EVAL_URL}}
    - name: Install dependencies
      run: pip install transformers==2.11 seqeval sklearn
    - name: Run Eval
      run: cd GLUECoS_Eval && ./eval.sh ../results.zip
